app:
  services:
    identity: "${IDENTITY_SERVICE:http://localhost:8001/identity}"
    # identity: http://identity-service:8001/identity
    # identity: http://localhost:8001/identity
  redis:
    redis-host: ${REDIS_HOST:127.0.0.1}
    redis-port: ${REDIS_PORT:6379}
    ttl_student_schedule: 300 # seconds
  security:
    jwt:
      signerKey: Tz1E7phK2u1hlLi2fTtDKqJx8gu+eAYoqSkGbQjKs7RHzz1yFqwt/DlJQ5BMlaipFwYOMvtg9cbej8dvP67tYg==

spring:
  config:
    import: optional:configserver:http://localhost:8101
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: schedule-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5510/schedule_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
  jpa: 
    hibernate: 
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties: 
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': false
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9095}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

server:
  port: 8086
  servlet:
    context-path: /lms_schedule_service
  error: 
    include-message: always
    
######
management:
  endpoints:
    web:
      exposure:
        include: '*'
#   info:
#     env:
#       enabled: true