app:
  services:
    identity: "${IDENTITY_SERVICE:http://localhost:8001/identity}"
    # identity: http://identity-service:8001/identity
    # identity: http://localhost:8001/identity
  redis:
    redis-host: ${REDIS_HOST:127.0.0.1}
    redis-port: ${REDIS_PORT:6379}
    ttl_student_schedule: 300 # seconds

spring:
  application:
    name: schedule_service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lms_system}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    # url: jdbc:postgresql://localhost:5432/lms_system
    # username: postgres
    # password: 123
  jpa: 
    hibernate: 
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': false
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1
server:
  port: 8086
  servlet:
    context-path: /lms_schedule_service
  error: 
    include-message: always
    
######